#!/bin/bash -e
# Matrix Calculator

dims() {

    if [ $# -gt "1" ]; #if number of files is greater than one
    then
        echo "error, too many arguments" 1>&2 #1>&2 means stderr
        return 1 #anything greater than 0 means false

    elif [ $# -eq 1 ] && [ ! -r $1 ] #if number of files is equal to one AND not readable
    then
        echo "error, file unreadable" 1>&2
        return 1

    else
        #saves count of lines in rows, $1 because it's the function's FIRST argument
        rows=$(wc -l < $1)

        #prints columns
        firstL=$(head -n 1 $1)
        cols=$(echo $firstL | grep -o " " | wc -l)
        ((cols++))

        #prints rows and columns
        echo $rows $cols

        return 0 #means true
    fi
}

datafilepath="datafile$$"

if [ "$1" = "dims" ];
then
    if [ $# = "2" ]
    then 
        $1 $2 #dims filename.txt

    elif [ $# = "1" ]
    then    
        cat > "$datafilepath"
        $1 "$datafilepath"

    else #if number of files is greater than one
        echo "error, too many arguments" 1>&2
        exit 1
    fi

else
    echo "Error 2" 1>&2
    exit 1
fi